services:
  db:
    image: postgres:13
    container_name: postgres_hotdog
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer-hotdog
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

  app:
    build: .
    container_name: hotdog_app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
